### ISSUE TITLE
NumberInputControl parse the string value to number before set the form value

### ISSUE THREAD

**Issue by AbderrazzakB** [kgnugur/formik-chakra-ui#35]
Currently, the NumberInputControl sets the FieldValue as a string. it would be good if it parses the string to a number before sets the FieldValue

**Comment by kgnugur** [comment]
Thank you for opening an issue, yes it could be nice. I will look into it today or tomorrow.

**Comment by AbderrazzakB** [comment]
> Thank you for opening an issue, yes it could be nice. I will look into it today or tomorrow.

I could help with this!

**Comment by kgnugur** [comment]
I took a look at it. I tried to parse a string to Int 'onChange' it of course works on non-float numbers. But floating number experience is not good.  When you start typing `2.`  it removes `.` on the fly. 
But this works --> type `23` then put `.` between --> `2.3`.
The workaround would be to parse it only on `onBlur`. But I don't think it's a good solution since it's not consistent and things could become messy for the API consumer.

If you have a suggestion it is of course welcome.
